package app.inkstave.shared.ui

import androidx.compose.ui.test.assertTextEquals
import androidx.compose.ui.test.junit4.createComposeRule
import androidx.compose.ui.test.onAllNodesWithText
import androidx.compose.ui.test.onNodeWithTag
import androidx.compose.ui.test.onNodeWithText
import androidx.compose.ui.test.performClick
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import app.cash.sqldelight.driver.android.AndroidSqliteDriver
import app.inkstave.shared.importer.LibraryImporter
import app.inkstave.shared.importer.PickedFile
import app.inkstave.shared.index.InkstaveDatabase
import app.inkstave.shared.index.LibraryIndexRepository
import org.junit.After
import org.junit.Before
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import java.io.File

/**
 * Android instrumented counterpart to `client/shared/src/desktopTest/.../ui/AppUiTest.kt`
 * -- same scenario (`docs/testing-strategy.md`'s M1 UI-level end-to-end gap:
 * "import a PDF, see it in the library, open it, turn pages"), driven the
 * same way, against the real [App]/[LibraryScreen]/[ViewerScreen]
 * composables via real simulated UI interaction, only running on a real
 * Android instrumentation target instead of headlessly on the JVM.
 *
 * **Status: written, not yet build-verified or run.** This file exists so
 * the test is ready and correct rather than only theorized, but as of this
 * writing it is not wired into `client/shared/build.gradle.kts` (no
 * `androidInstrumentedTest` dependencies or `instrumentedTestVariant`
 * source-set-tree configuration were added) and has not been compiled or
 * executed against a connected device/emulator. Two connected AVDs exist on
 * this development machine (`Medium_Phone_API_36.1`, `meowdoku-dev`, both
 * `/dev/kvm`-accelerated) and would very likely make running this feasible,
 * but launching a full Android emulator is a heavyweight, multi-minute,
 * resource-intensive operation on a machine independently confirmed (twice,
 * during the M0 and M1 passes) to be in active concurrent use by its owner
 * -- that was judged too disruptive to do autonomously in an unattended
 * verification pass, as distinct from a genuine technical blocker. Wiring
 * the Gradle dependencies was *also* not attempted blind: doing so needs
 * new test-only artifacts (an androidx.test/Compose instrumented-test JUnit4
 * runner) that, like the desktop `compose.uiTest` dependency, are not
 * already present in this machine's Gradle cache and could not be resolved
 * in this session (see this pass's report for why -- a JVM-specific
 * outbound-network restriction unrelated to this code). Getting an
 * unfamiliar part of the Kotlin Gradle Plugin's Android-target API wrong
 * with no way to compile-check it risked breaking `shared/build.gradle.kts`
 * script evaluation for every currently-green task, not just this one --
 * worse than leaving this wiring for whoever picks it up next with working
 * network access.
 *
 * To finish this: add `androidx.test.ext:junit`, `androidx.test:runner`, and
 * `androidx.compose.ui:ui-test-junit4-android` to a `androidInstrumentedTest`
 * source set in `shared/build.gradle.kts` (with the corresponding
 * `androidTarget { ... }` instrumented-test-variant wiring current Compose
 * Multiplatform + Kotlin Gradle Plugin docs specify), then:
 * `./gradlew :shared:connectedAndroidTest` against a booted emulator or
 * connected device.
 */
@RunWith(AndroidJUnit4::class)
class AppInstrumentedTest {
    @get:Rule
    val composeTestRule = createComposeRule()

    private lateinit var libraryDir: File
    private lateinit var driver: AndroidSqliteDriver
    private lateinit var index: LibraryIndexRepository
    private lateinit var importer: LibraryImporter

    @Before
    fun setUp() {
        val context = InstrumentationRegistry.getInstrumentation().targetContext
        libraryDir = File(context.cacheDir, "inkstave-ui-test-${System.nanoTime()}").apply { mkdirs() }
        driver = AndroidSqliteDriver(InkstaveDatabase.Schema, context, name = null) // in-memory: name = null
        index = LibraryIndexRepository(driver)
        importer = LibraryImporter(libraryDir, index)
    }

    @After
    fun tearDown() {
        driver.close()
        libraryDir.deleteRecursively()
    }

    /** A minimal single-page PDF, hand-constructed rather than generated by a
     * library -- see the desktop equivalent test for why it's generated in-test
     * rather than a committed binary fixture; Android has no PDFBox dependency
     * (M1 uses the platform `PdfRenderer` there instead), so there's no equally
     * convenient generator available on this target. **Caveat, part of why this
     * whole file is flagged unverified above:** these exact bytes (in particular
     * the xref table's byte offsets, left as placeholders) have not been checked
     * against a real `PdfRenderer` instance -- pdfium's parser may be strict
     * about xref correctness even for a single-page document. Verify this
     * specific fixture first if this test fails for a PDF-parsing reason once
     * it's actually run, before assuming the UI logic itself is wrong. */
    private fun tinyOnePagePdfBytes(): ByteArray {
        val pdf =
            """
            %PDF-1.4
            1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
            2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj
            3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 200 200]>>endobj
            xref
            0 4
            0000000000 65535 f
            trailer<</Size 4/Root 1 0 R>>
            startxref
            0
            %%EOF
            """.trimIndent()
        return pdf.toByteArray()
    }

    @Test
    fun importAPdfViaTheUiSeeItInTheLibraryOpenItAndTurnPages() {
        composeTestRule.setContent {
            App(
                libraryIndex = index,
                importer = importer,
                pickPdf = { PickedFile(bytes = tinyOnePagePdfBytes(), displayName = "Sonata.pdf") },
                pickImages = { emptyList() },
            )
        }

        composeTestRule.onNodeWithTag(TestTags.EMPTY_LIBRARY).assertExists()

        composeTestRule.onNodeWithTag(TestTags.IMPORT_FAB).performClick()
        composeTestRule.onNodeWithTag(TestTags.IMPORT_PDF_MENU_ITEM).performClick()

        composeTestRule.waitUntil(timeoutMillis = 10_000) {
            composeTestRule.onAllNodesWithText("Sonata").fetchSemanticsNodes().isNotEmpty()
        }
        composeTestRule.onNodeWithText("Sonata").assertExists()

        composeTestRule.onNodeWithText("Sonata").performClick()
        composeTestRule.waitForIdle()
        composeTestRule.onNodeWithTag(TestTags.VIEWER_PAGE_INDICATOR).assertTextEquals("1 / 1")

        composeTestRule.onNodeWithTag(TestTags.VIEWER_BACK_BUTTON).performClick()
        composeTestRule.waitForIdle()
        composeTestRule.onNodeWithText("Sonata").assertExists()
    }
}
